baseURL = "https://github.io"
languageCode = "en-us"
title = "Sorifa Alam | Data Science Portfolio"
theme = "hugo-profile"

[params]
  # Navbar Title
  [params.navbar]
    enable = true
    brandName = "Sorifa Alam"

  # Top Profile Hero Banner
  [params.home]
    enable = true
    name = "Sorifa Alam"
    profession = "M.Sc. Data Science Student & Researcher"
    bio = "Core research and project experience spanning across advanced machine learning model architecture, deep learning frameworks, and deep graph neural networks for security. Passionate about academic writing."
    image = "https://github.com"

  # Core Text About Box
  [params.about]
    enable = true
    title = "About Me"
    content = "I'm an M.Sc. student in Computer Science and Engineering (Major: Data Science) at Daffodil International University where I also completed my B.Sc. in Computing and Information Systems (Major: Artificial Intelligence in IoT) with a CGPA of 3.89/4.00. My core research spans advanced machine learning architecture, deep learning frameworks, and deep graph neural networks for security."

  # Direct Contact Info
  [params.contact]
    enable = true
    email = "262-25-008@diu.edu.bd"
    phone = "+8801300981028"
    address = "Tongi-Gazipur, Bangladesh"
    github = "https://github.com"
